### ISSUE TITLE
Docker compose is not able to build the Jupyter image. 

### ISSUE THREAD

**Issue by AlbertRemke** [oer4sdi/OER-spatial-data-streaming#36]
Error messages in the build process:
 > Jupyter command `jupyter-nbextension` not found.
------
failed to solve: process "/bin/sh -c jupyter nbextension enable --py --sys-prefix ipyleaflet" did not complete successfully: exit code: 1

**Comment by foost** [comment]
Error still occurs.

**Comment by AlbertRemke** [comment]
issues have been fixed, see commits: 
[- b56a3571c17e800608e013a625ea9f47c69834dd](https://github.com/oer4sdi/OER-spatial-data-streaming/commit/b56a3571c17e800608e013a625ea9f47c69834dd)
- https://github.com/oer4sdi/OER-spatial-data-streaming/commit/e219b7886906935b45fab0243a46216c329c6172

**Comment by AlbertRemke** [comment]
..
